---
title: "Análisis exploratorio"
author: "Tamara Ricardo"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
# Carga paquetes ----------------------------------------------------------
pacman::p_load(
  # Statistical analysis
  survival,
  # Inference and residuals
  DHARMa,
  performance,
  # Exploratory analysis
  compareGroups,
  gtsummary,
  dlookr,
  # Plot tools
  survminer,
  # Data management
  rio,
  janitor,
  tidyverse
)

# Carga datos -------------------------------------------------------------
data <- import("datos_CA_COVID_clean.xlsx") %>% 
  ### Variables categóricas a factor
  mutate(across(where(is.character)|matches("idpte"),
                as.factor)) %>%
  ## Cambia nivel de referencia
  mutate_at("tipo_CA1", .funs = ~ fct_relevel(.x, "Sólido")) %>% 
  ## COVID durante estudio (numérico)
  mutate(covid_est_num = if_else(dx_covid_estudio=="Si", 1, 0))
```

### Valores ausentes
```{r}
### Explora valores faltantes
data %>% plot_na_pareto(only_na = T)
```

\pagebreak

### Descripción de la muestra
```{r}
### Frecuencia variables muestra completa
data %>% 
  tbl_summary(missing = "no",
              include = c(sexo, edad, edad_cat, starts_with("comorb"),
                          icd10_cat1, tipo_CA1, evol_CA1, ecog_num,
                          gravedad_CA, mas_un_tumor, metastasis,
                          trat_quimio_rtx, trat_rtx, trat_quimio,
                          ciclos_quimio, dx_covid_estudio))
```

\pagebreak

### Compara pacientes con y sin diagnóstico de COVID-19
```{r}
data %>% 
  tbl_summary(by = dx_covid_estudio,
              missing = "no", percent = "col",
              include = c(sexo, edad, edad_cat, comorb_met, comorb_cvg, 
                          comorb_res, comorb_hiv, comorb_alc, comorb_tab,
                          tipo_CA1, evol_CA1, ecog_num,
                          gravedad_CA, mas_un_tumor, metastasis,
                          trat_quimio_rtx, trat_rtx, trat_quimio,
                          ciclos_quimio)) %>% 
  add_p() %>% 
  bold_p() %>% 
  bold_labels()
```

\pagebreak

### Curvas de supervivencia
```{r}
### Crea objeto supervivencia
surv <- with(data, Surv(dias_ini_covid, covid_est_num))
```

#### Modelo solo intercepto
```{r}
### Modelo solo intercepto
fit<- survfit(surv ~ 1, data = data)

fit

## Gráfico
ggsurvplot(fit = fit, data = data, conf.int = T, ylim = c(.75,1))
```

#### Sexo
```{r}
# Supervivencia por sexo --------------------------------------------------
fit_sex <- survfit(surv ~ sexo, data = data)

## Gráfico
ggsurvplot(fit = fit_sex, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ sexo, data = data) # p= 0.4
```

#### Grupo etario
```{r}
# Supervivencia por grupo etario ------------------------------------------
fit_edad <- survfit(surv ~ edad_cat, data = data)

## Gráfico
ggsurvplot(fit = fit_edad, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ edad_cat, data = data) # p= 0.2
```

#### Tipo de cáncer
```{r}
# Supervivencia por tipo de cáncer ----------------------------------------
### Sólido vs hematológico
fit_tipo <- survfit(surv ~ tipo_CA1, data = data)

## Gráfico
ggsurvplot(fit = fit_tipo, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ tipo_CA1, data = data) # p= 0.06
```

#### Tipo de tratamiento
```{r}
# Supervivencia por tipo tratamiento --------------------------------------
fit_trat <- survfit(surv ~ trat_quimio_rtx, data = data)

## Gráfico
ggsurvplot(fit = fit_trat, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ trat_quimio_rtx, data = data) # p= 0.04*
```

#### Quimioterapia
```{r}

### Quimioterapia
fit_quim <- survfit(surv ~ trat_quimio, data = data)

## Gráfico
ggsurvplot(fit = fit_quim, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ trat_quimio, data = data) # p= 0.01*
```

#### Más de un tumor
```{r}
### Más de un tumor
fit_mas <- survfit(surv ~ mas_un_tumor, data = data)

## Gráfico
ggsurvplot(fit = fit_mas, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ mas_un_tumor, data = data) # p= 0.6
```

#### Metástasis
```{r}
### Metástasis
fit_met <- survfit(surv ~ metastasis, data = data)

## Gráfico
ggsurvplot(fit = fit_met, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ metastasis, data = data) # p= 0.8
```

#### Gravedad
```{r}
### Gravedad del cáncer
fit_grav <- survfit(surv ~ gravedad_CA, data = data)

## Gráfico
ggsurvplot(fit = fit_grav, data = data, conf.int = T, ylim = c(.75,1), 
           risk.table = F)

## Compara funciones
survdiff(surv ~ gravedad_CA, data = data) # p= 0.7
```

### Regresión de Cox
```{r}
# Regresión de Cox --------------------------------------------------------
### Modelo full
fit_cox <- coxph(surv ~ tipo_CA1 + trat_quimio, data = data)

summary(fit_cox)

### Modelo s/ tipo cáncer
fit_cox1 <- update(fit_cox, ~.-tipo_CA1)

## Compara modelos
anova(fit_cox, fit_cox1)

## AIC
performance(fit_cox1, metrics = "common")

## Coeficientes
tbl_regression(fit_cox1, exponentiate = T)

## Gráfico
ggadjustedcurves(fit = fit_cox1, data = data, 
                 variable = "trat_quimio", ylim = c(.75, 1))

## Residuales
ggcoxdiagnostics(fit_cox1, type = "schoenfeld")

ggcoxdiagnostics(fit_cox1, type = "martingale")
```

